version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=${URL}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${DB_PW}
      - DB_DATABASE=bookstackapp
    volumes:
      - /data/bookstack/config:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.entrypoints=http"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.domain.com`)"
      - "traefik.http.middlewares.bookstack-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bookstack.middlewares=bookstack-https-redirect"
      - "traefik.http.routers.bookstack-secure.entrypoints=https"
      - "traefik.http.routers.bookstack-secure.rule=Host(`bookstack.domain.com`)"
      - "traefik.http.routers.bookstack-secure.tls=true"
      - "traefik.http.routers.bookstack-secure.service=bookstack"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_PW}
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DB_PW}
    volumes:
      - /data/bookstack/database/config:/config
    restart: unless-stopped
    networks:
      - default
networks:
  proxy:
    external: true