version: '3'
services:
  rss-bridge:
    image: rssbridge/rss-bridge:latest
    volumes:
      - ./config:/config
    ports:
      - 3500:80
    environment:
      - RSSBRIDGE_SYSTEM_ENABLED_BRIDGES=MangaDexBridge
    restart: unless-stopped
