version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: "1000:1000"
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "/data/navidrome:/data"
      - "/data/nextcloud/admin/files/Music:/music:ro"